### ISSUE TITLE
wrong npm package name?

### ISSUE THREAD

**Issue by Slach** [elo1lson/lapce-css#1]
maybe instead `npm install -g vscode-css-language-server`
need `npm install -g vscode-css-languageservice` ?

**Comment by Slach** [comment]
or `npm install -g css-language-server`

**Comment by elo1lson** [comment]
Thank you for bringing this to my attention. I apologize for not checking if the `vscode-css-language-server` package was available on npm before using it in the creation of the plugin. I mistakenly assumed it was readily available.

I appreciate your suggestion to include the package as a dependency in the plugin, and I will certainly consider it for future updates. In the meantime, I recommend following the installation steps provided in the repository's README file to ensure the necessary dependencies are properly set up.

Once again, I apologize for any inconvenience caused, and thank you for your understanding.

**Comment by insign** [comment]
@elo1lson I'm sorry but makes no sense what you said. @Slach didn't made any suggestion, he, like me are just trying figure out how to use the plugin. The `vscode-css-language-server` is not available in npm registry.... How to fix?

**Comment by elo1lson** [comment]
@insign I'm sorry for what happened, due to lack of time I still haven't corrected the package name, you just have to install the correct package using `npm i -g vscode-langservers-extracted`, done that, the package `vscode-css-language-server ` which is the basis for the plugin to work, it will be available and the plugin will work, my mistake was creating the README with wrong instructions
